# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - draconisloadtest-client(Production), Build and deploy NodeJS app

on:
  push:
    branches:
      - develop

env:
  apiUrl: https://draconisloadtest-api.azurewebsites.net
  tokenEndpoint: https://draconisloadtest-api.azurewebsites.net/connect/token

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: 'Set up Node.js version'
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.0'

    - name: 'npm install, build, and test'
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: draconisloadtest-client
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AB543BD4A1F94C3DA9F3803E10C225B6 }}
        package: ./dist
